enum {
    FOCUS_QUIT = 0,
    FOCUS_PLAYER_SELECT,
    FOCUS_PLAYER,
    FOCUS_PARTY_SIZE,
    FOCUS_FOOD_GOLD,
    FOCUS_MIXTURES,
    FOCUS_REAGENTS,
    FOCUS_VIRTUES,
    FOCUS_RUNES,
    FOCUS_STONES,
    FOCUS_ITEMS
};


void edit(void);
